package com.anvritai.abhay.domain.document;

public enum DocumentType {
    SALES_INVOICE, PURCHASE_INVOICE, CREDIT_NOTE, DEBIT_NOTE, RECEIPT, PAYMENT_ADVICE,
    BANK_STATEMENT, GST_RETURN, GST_NOTICE, PURCHASE_ORDER, QUOTATION, DELIVERY_CHALLAN, OTHER
}
