package com.anvritai.abhay.domain.memory;

public enum MemoryType {
    VENDOR_MEMORY, CUSTOMER_MEMORY, LEDGER_MAPPING_MEMORY, GST_TREATMENT_MEMORY,
    VOUCHER_PATTERN_MEMORY, INVOICE_PATTERN_MEMORY, DOCUMENT_CORRECTION_MEMORY,
    BANK_RECONCILIATION_MEMORY, INVENTORY_MEMORY, USER_PREFERENCE_MEMORY, COMPANY_BEHAVIOR_MEMORY
}
