package com.anvritai.abhay.service;
import static com.anvritai.abhay.api.JobDtos.*;
import com.anvritai.abhay.domain.*; import com.anvritai.abhay.domain.automation.BackgroundJob;
import com.anvritai.abhay.repository.*; import com.anvritai.abhay.repository.automation.BackgroundJobRepository;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Instant; import java.util.*; import org.slf4j.MDC; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service public class BackgroundJobService {
 private static final Set<String> TYPES=Set.of("DOCUMENT_PROCESSING","MEMORY_REBUILD","GST_SUMMARY","INVENTORY_RECALCULATION","BANK_RECONCILIATION_SCAN","SCHEDULED_REPORT","AUTOMATION_RULE");
 private final BackgroundJobRepository jobs; private final CompanyRepository companies; private final UserRepository users; private final CompanyAccessService access; private final AuditService audit; private final ObjectMapper json;
 public BackgroundJobService(BackgroundJobRepository jobs,CompanyRepository companies,UserRepository users,CompanyAccessService access,AuditService audit,ObjectMapper json){this.jobs=jobs;this.companies=companies;this.users=users;this.access=access;this.audit=audit;this.json=json;}
 @Transactional public JobResponse enqueue(UUID userId,UUID companyId,EnqueueJobRequest request){access.requireRole(companyId,userId,RoleCode.OWNER,RoleCode.ADMIN,RoleCode.ACCOUNTANT);String type=request.jobType().trim().toUpperCase(Locale.ROOT);if(!TYPES.contains(type))throw new AccountingRuleException("Unsupported background job type.");Company company=company(companyId);User user=user(userId);BackgroundJob j=new BackgroundJob();j.setCompany(company);j.setCreatedBy(user);j.setJobType(type);j.setStatus("QUEUED");j.setPayloadJson(write(request.payload()));j.setScheduledAt(request.scheduledAt()==null?Instant.now():request.scheduledAt());j.setMaxAttempts(request.maxAttempts()==null?3:request.maxAttempts());j.setCorrelationId(correlation());jobs.save(j);audit.record(company,user,"BACKGROUND_JOB_QUEUED","BACKGROUND_JOB",j.getId(),Map.of("jobType",type));return response(j);}
 @Transactional(readOnly=true) public List<JobResponse> list(UUID userId,UUID companyId){access.requireMembership(companyId,userId);return jobs.findAllByCompanyIdOrderByCreatedAtDesc(companyId).stream().map(this::response).toList();}
 @Transactional public JobResponse run(UUID userId,UUID companyId,UUID id){access.requireRole(companyId,userId,RoleCode.OWNER,RoleCode.ADMIN);BackgroundJob j=jobs.findByIdAndCompanyId(id,companyId).orElseThrow(()->new NotFoundException("Background job not found."));if(!"QUEUED".equals(j.getStatus())&&!"FAILED".equals(j.getStatus()))throw new AccountingRuleException("Only queued or failed jobs can run.");complete(j,"Job foundation completed safely.");return response(j);}
 @Transactional public int processDue(){int count=0;for(BackgroundJob j:jobs.findTop20ByStatusAndScheduledAtLessThanEqualOrderByScheduledAt("QUEUED",Instant.now())){complete(j,"Queued work completed.");count++;}return count;}
 private void complete(BackgroundJob j,String message){j.setStatus("RUNNING");j.setStartedAt(Instant.now());j.setAttempts(j.getAttempts()+1);j.setResultJson(write(Map.of("accepted",true,"message",message)));j.setStatus("SUCCEEDED");j.setCompletedAt(Instant.now());}
 private JobResponse response(BackgroundJob j){return new JobResponse(j.getId(),j.getJobType(),j.getStatus(),map(j.getPayloadJson()),map(j.getResultJson()),j.getAttempts(),j.getMaxAttempts(),j.getScheduledAt(),j.getStartedAt(),j.getCompletedAt(),j.getCorrelationId());}
 private Company company(UUID id){return companies.findById(id).orElseThrow(()->new NotFoundException("Company not found."));}private User user(UUID id){return users.findById(id).orElseThrow(()->new NotFoundException("Account not found."));}
 private String write(Object o){try{return json.writeValueAsString(o==null?Map.of():o);}catch(Exception e){throw new AccountingRuleException("Job payload is invalid.");}}private Map<String,Object> map(String s){if(s==null)return Map.of();try{return json.readValue(s,new TypeReference<>(){});}catch(Exception e){return Map.of();}}
 private String correlation(){String value=MDC.get("correlationId");return value==null?UUID.randomUUID().toString():value;}
}
