package com.anvritai.abhay.service;
import static com.anvritai.abhay.api.SettingsDtos.*;
import com.anvritai.abhay.domain.*; import com.anvritai.abhay.domain.automation.CompanySetting; import com.anvritai.abhay.repository.*; import com.anvritai.abhay.repository.automation.CompanySettingRepository;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class CompanySettingsService {
 private static final Set<String> CATEGORIES=Set.of("COMPANY","ACCOUNTING","GST","INVENTORY","BANK","NOTIFICATION","AUTOMATION","AI_MEMORY"); private static final Set<String> TYPES=Set.of("STRING","BOOLEAN","INTEGER","DECIMAL","JSON");
 private final CompanySettingRepository settings;private final CompanyRepository companies;private final UserRepository users;private final CompanyAccessService access;private final AuditService audit;
 public CompanySettingsService(CompanySettingRepository settings,CompanyRepository companies,UserRepository users,CompanyAccessService access,AuditService audit){this.settings=settings;this.companies=companies;this.users=users;this.access=access;this.audit=audit;}
 @Transactional(readOnly=true) public List<SettingResponse> list(UUID userId,UUID companyId,String category){access.requireMembership(companyId,userId);String c=category==null?null:category(category);return (c==null?settings.findAllByCompanyIdOrderByCategoryAscSettingKeyAsc(companyId):settings.findAllByCompanyIdAndCategoryOrderBySettingKey(companyId,c)).stream().map(this::response).toList();}
 @Transactional public SettingResponse put(UUID userId,UUID companyId,String category,SettingRequest request){access.requireRole(companyId,userId,RoleCode.OWNER,RoleCode.ADMIN);String c=category(category);String type=request.valueType().trim().toUpperCase(Locale.ROOT);if(!TYPES.contains(type))throw new AccountingRuleException("Unsupported setting value type.");validateValue(type,request.value());Company company=companies.findById(companyId).orElseThrow(()->new NotFoundException("Company not found."));User user=users.findById(userId).orElseThrow(()->new NotFoundException("Account not found."));String key=request.key().trim().toLowerCase(Locale.ROOT);CompanySetting s=settings.findByCompanyIdAndCategoryAndSettingKey(companyId,c,key).orElseGet(CompanySetting::new);s.setCompany(company);s.setCategory(c);s.setSettingKey(key);s.setSettingValue(request.value().trim());s.setValueType(type);s.setUpdatedBy(user);settings.save(s);audit.record(company,user,"COMPANY_SETTING_UPDATED","COMPANY_SETTING",s.getId(),Map.of("category",c,"key",key));return response(s);}
 private void validateValue(String type,String value){try{switch(type){case "BOOLEAN"->{if(!Set.of("true","false").contains(value.toLowerCase(Locale.ROOT)))throw new IllegalArgumentException();}case "INTEGER"->Long.parseLong(value);case "DECIMAL"->new java.math.BigDecimal(value);default->{}}}catch(RuntimeException e){throw new AccountingRuleException("Setting value does not match its declared type.");}}
 private String category(String v){String x=v.trim().toUpperCase(Locale.ROOT);if(!CATEGORIES.contains(x))throw new AccountingRuleException("Unsupported settings category.");return x;}private SettingResponse response(CompanySetting s){return new SettingResponse(s.getId(),s.getCategory(),s.getSettingKey(),s.getSettingValue(),s.getValueType(),s.getUpdatedAt());}
}
