package com.anvritai.abhay;

import static org.hamcrest.Matchers.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.anvritai.abhay.domain.AuditLog;import com.anvritai.abhay.repository.AuditLogRepository;import com.anvritai.abhay.repository.memory.MemoryEventRepository;import com.fasterxml.jackson.databind.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @TestMethodOrder(MethodOrderer.OrderAnnotation.class) @TestInstance(TestInstance.Lifecycle.PER_CLASS)
class EnterpriseHardeningIntegrationTests{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired MemoryEventRepository memoryEvents;@Autowired AuditLogRepository auditLogs;
 private Workspace owner;private UUID bankRule;private UUID gstRule;private UUID notification;private UUID job;private String viewerToken;
 @BeforeAll void setup()throws Exception{owner=workspace("enterprise");}

 @Test @Order(1) void liveEndpointIsPublic()throws Exception{mvc.perform(get("/live")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("UP"));}
 @Test @Order(2) void healthReportsDatabaseAndFlyway()throws Exception{mvc.perform(get("/health")).andExpect(status().isOk()).andExpect(jsonPath("$.database").value("UP")).andExpect(jsonPath("$.flyway").value("UP"));}
 @Test @Order(3) void readinessEndpointIsPublic()throws Exception{mvc.perform(get("/ready")).andExpect(status().isOk()).andExpect(jsonPath("$.scheduler").value("UP"));}
 @Test @Order(4) void healthDoesNotExposeSecrets()throws Exception{String body=mvc.perform(get("/health")).andReturn().getResponse().getContentAsString();assertFalse(body.contains("DATABASE_URL"));assertFalse(body.toLowerCase(Locale.ROOT).contains("password"));}
 @Test @Order(5) void securityHeadersArePresent()throws Exception{mvc.perform(get("/live")).andExpect(header().string("X-Frame-Options","DENY")).andExpect(header().string("X-Content-Type-Options","nosniff"));}
 @Test @Order(6) void requestIdIsReturned()throws Exception{mvc.perform(get("/live")).andExpect(header().exists("X-Request-ID")).andExpect(header().exists("X-Correlation-ID"));}
 @Test @Order(7) void suppliedCorrelationIdIsEchoed()throws Exception{mvc.perform(get("/live").header("X-Correlation-ID","enterprise-test-7")).andExpect(header().string("X-Correlation-ID","enterprise-test-7"));}
 @Test @Order(8) void openApiIsAvailable()throws Exception{mvc.perform(get("/v3/api-docs")).andExpect(status().isOk()).andExpect(jsonPath("$.info.title").value("ABHAY Accounting OS API"));}
 @Test @Order(9) void automationTemplatesAreSeeded()throws Exception{mvc.perform(auth(get(path("/automation/templates")))).andExpect(status().isOk()).andExpect(jsonPath("$",hasSize(5)));}
 @Test @Order(10) void automationRuleCanBeCreated()throws Exception{MvcResult r=mvc.perform(auth(post(path("/automation/rules"))).contentType(MediaType.APPLICATION_JSON).content(rule("Bank Review","BANK_UNRECONCILED","DAILY","IN_APP",Map.of()))).andExpect(status().isOk()).andExpect(jsonPath("$.active").value(true)).andReturn();bankRule=id(r);}
 @Test @Order(11) void automationRulesCanBeListed()throws Exception{mvc.perform(auth(get(path("/automation/rules")))).andExpect(status().isOk()).andExpect(jsonPath("$[*].id",hasItem(bankRule.toString())));}
 @Test @Order(12) void unsupportedRuleTypeIsRejected()throws Exception{mvc.perform(auth(post(path("/automation/rules"))).contentType(MediaType.APPLICATION_JSON).content(rule("Bad","UNKNOWN","DAILY","IN_APP",Map.of()))).andExpect(status().isUnprocessableEntity());}
 @Test @Order(13) void unsupportedScheduleIsRejected()throws Exception{mvc.perform(auth(post(path("/automation/rules"))).contentType(MediaType.APPLICATION_JSON).content(rule("Bad","LOW_STOCK","HOURLY","IN_APP",Map.of()))).andExpect(status().isUnprocessableEntity());}
 @Test @Order(14) void unsupportedChannelIsRejected()throws Exception{mvc.perform(auth(post(path("/automation/rules"))).contentType(MediaType.APPLICATION_JSON).content(rule("Bad","LOW_STOCK","DAILY","SMS",Map.of()))).andExpect(status().isUnprocessableEntity());}
 @Test @Order(15) void automationRuleCanBeUpdated()throws Exception{mvc.perform(auth(patch(path("/automation/rules/"+bankRule))).contentType(MediaType.APPLICATION_JSON).content(rule("Daily Bank Review","BANK_UNRECONCILED","DAILY","IN_APP",Map.of()))).andExpect(status().isOk()).andExpect(jsonPath("$.name").value("Daily Bank Review"));}
 @Test @Order(16) void gstDueRuleCanBeCreated()throws Exception{MvcResult r=mvc.perform(auth(post(path("/automation/rules"))).contentType(MediaType.APPLICATION_JSON).content(rule("GST Due","GST_DUE","DAILY","EMAIL",Map.of("dueDate",java.time.LocalDate.now().toString(),"daysBefore",5)))).andExpect(status().isOk()).andReturn();gstRule=id(r);}
 @Test @Order(17) void automationRunEvaluatesSignals()throws Exception{mvc.perform(auth(post(path("/automation/rules/"+gstRule+"/run")))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("SUCCESS")).andExpect(jsonPath("$.matchedCount").value(1));}
 @Test @Order(18) void externalNotificationIsDeliveryReady()throws Exception{MvcResult r=mvc.perform(auth(get(path("/automation/notifications")))).andExpect(status().isOk()).andExpect(jsonPath("$[0].deliveryStatus").value("READY")).andReturn();notification=UUID.fromString(node(r).get(0).get("id").asText());}
 @Test @Order(19) void notificationCanBeMarkedRead()throws Exception{mvc.perform(auth(post(path("/automation/notifications/"+notification+"/read")))).andExpect(status().isOk()).andExpect(jsonPath("$.readAt").isNotEmpty());}
 @Test @Order(20) void automationDashboardHasRunCounts()throws Exception{mvc.perform(auth(get(path("/automation/dashboard")))).andExpect(status().isOk()).andExpect(jsonPath("$.activeRules").value(2)).andExpect(jsonPath("$.totalRuns").value(1));}
 @Test @Order(21) void noMatchRunIsSafe()throws Exception{mvc.perform(auth(post(path("/automation/rules/"+bankRule+"/run")))).andExpect(status().isOk()).andExpect(jsonPath("$.matchedCount").value(0)).andExpect(jsonPath("$.summary").value("No action is currently required."));}
 @Test @Order(22) void automationRunCreatesMemoryEvent(){assertTrue(memoryEvents.findAllByCompanyIdOrderByOccurredAtDesc(owner.companyId()).stream().anyMatch(e->e.getEventType().equals("AUTOMATION_RULE_RUN")));}
 @Test @Order(23) void jobCanBeQueued()throws Exception{MvcResult r=mvc.perform(auth(post(path("/jobs"))).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("jobType","MEMORY_REBUILD","payload",Map.of("scope","patterns"),"maxAttempts",3)))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("QUEUED")).andReturn();job=id(r);}
 @Test @Order(24) void jobsCanBeListed()throws Exception{mvc.perform(auth(get(path("/jobs")))).andExpect(status().isOk()).andExpect(jsonPath("$[*].id",hasItem(job.toString())));}
 @Test @Order(25) void queuedJobCanRun()throws Exception{mvc.perform(auth(post(path("/jobs/"+job+"/run")))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("SUCCEEDED")).andExpect(jsonPath("$.attempts").value(1));}
 @Test @Order(26) void completedJobCannotReplay()throws Exception{mvc.perform(auth(post(path("/jobs/"+job+"/run")))).andExpect(status().isUnprocessableEntity());}
 @Test @Order(27) void invalidJobTypeIsRejected()throws Exception{mvc.perform(auth(post(path("/jobs"))).contentType(MediaType.APPLICATION_JSON).content("{\"jobType\":\"SHELL_COMMAND\",\"payload\":{}}" )).andExpect(status().isUnprocessableEntity());}
 @Test @Order(28) void settingCanBeCreated()throws Exception{mvc.perform(auth(put(path("/settings/accounting"))).contentType(MediaType.APPLICATION_JSON).content("{\"key\":\"rounding_mode\",\"value\":\"HALF_UP\",\"valueType\":\"STRING\"}" )).andExpect(status().isOk()).andExpect(jsonPath("$.category").value("ACCOUNTING"));}
 @Test @Order(29) void settingUpsertKeepsOneRecord()throws Exception{mvc.perform(auth(put(path("/settings/accounting"))).contentType(MediaType.APPLICATION_JSON).content("{\"key\":\"rounding_mode\",\"value\":\"HALF_EVEN\",\"valueType\":\"STRING\"}" )).andExpect(status().isOk());mvc.perform(auth(get(path("/settings")).param("category","ACCOUNTING"))).andExpect(jsonPath("$",hasSize(1))).andExpect(jsonPath("$[0].value").value("HALF_EVEN"));}
 @Test @Order(30) void allSettingsCanBeListed()throws Exception{mvc.perform(auth(get(path("/settings")))).andExpect(status().isOk()).andExpect(jsonPath("$[0].key").value("rounding_mode"));}
 @Test @Order(31) void invalidSettingsCategoryIsRejected()throws Exception{mvc.perform(auth(put(path("/settings/secrets"))).contentType(MediaType.APPLICATION_JSON).content("{\"key\":\"x\",\"value\":\"x\",\"valueType\":\"STRING\"}" )).andExpect(status().isUnprocessableEntity());}
 @Test @Order(32) void invalidTypedSettingIsRejected()throws Exception{mvc.perform(auth(put(path("/settings/gst"))).contentType(MediaType.APPLICATION_JSON).content("{\"key\":\"enabled\",\"value\":\"maybe\",\"valueType\":\"BOOLEAN\"}" )).andExpect(status().isUnprocessableEntity());}
 @Test @Order(33) void globalSearchFindsSeededLedger()throws Exception{mvc.perform(auth(get(path("/search")).param("q","Cash"))).andExpect(status().isOk()).andExpect(jsonPath("$.results[?(@.type == 'LEDGER')]").isNotEmpty());}
 @Test @Order(34) void globalSearchRejectsShortQueries()throws Exception{mvc.perform(auth(get(path("/search")).param("q","x"))).andExpect(status().isUnprocessableEntity());}
 @Test @Order(35) void globalSearchHonorsLimit()throws Exception{mvc.perform(auth(get(path("/search")).param("q","Account").param("limit","1"))).andExpect(status().isOk()).andExpect(jsonPath("$.results",hasSize(lessThanOrEqualTo(1))));}
 @Test @Order(36) void jsonExportWorks()throws Exception{mvc.perform(auth(get(path("/exports/ledgers")).param("format","JSON"))).andExpect(status().isOk()).andExpect(content().contentType(MediaType.APPLICATION_JSON));}
 @Test @Order(37) void csvExportWorks()throws Exception{mvc.perform(auth(get(path("/exports/vouchers")).param("format","CSV"))).andExpect(status().isOk()).andExpect(header().string("Content-Disposition",containsString(".csv"))).andExpect(content().string(containsString("record_id")));}
 @Test @Order(38) void pdfExportWorks()throws Exception{MvcResult r=mvc.perform(auth(get(path("/exports/invoices")).param("format","PDF"))).andExpect(status().isOk()).andExpect(content().contentType(MediaType.APPLICATION_PDF)).andReturn();assertTrue(r.getResponse().getContentAsByteArray().length>100);}
 @Test @Order(39) void excelReadyExportWorks()throws Exception{mvc.perform(auth(get(path("/exports/settings")).param("format","EXCEL"))).andExpect(status().isOk()).andExpect(content().contentType("application/vnd.ms-excel"));}
 @Test @Order(40) void companyBackupIsZip()throws Exception{MvcResult r=mvc.perform(auth(post(path("/backup")))).andExpect(status().isOk()).andExpect(content().contentType("application/zip")).andReturn();byte[] b=r.getResponse().getContentAsByteArray();assertEquals('P',b[0]);assertEquals('K',b[1]);}
 @Test @Order(41) void unsupportedExportIsRejected()throws Exception{mvc.perform(auth(get(path("/exports/passwords")).param("format","JSON"))).andExpect(status().isUnprocessableEntity());}
 @Test @Order(42) void crossCompanyAutomationAccessIsDenied()throws Exception{Workspace other=workspace("other-enterprise");mvc.perform(get(path("/automation/rules")).header("Authorization","Bearer "+other.token())).andExpect(status().isForbidden());}
 @Test @Order(43) void viewerCannotWriteAutomation()throws Exception{viewerToken=addViewer();mvc.perform(post(path("/automation/rules")).header("Authorization","Bearer "+viewerToken).contentType(MediaType.APPLICATION_JSON).content(rule("Viewer rule","LOW_STOCK","DAILY","IN_APP",Map.of()))).andExpect(status().isForbidden());}
 @Test @Order(44) void viewerCannotCreateBackup()throws Exception{mvc.perform(post(path("/backup")).header("Authorization","Bearer "+viewerToken)).andExpect(status().isForbidden());}
 @Test @Order(45) void protectedAutomationRequiresJwt()throws Exception{mvc.perform(get(path("/automation/rules"))).andExpect(status().isUnauthorized());}
 @Test @Order(46) void auditCapturesCorrelationId()throws Exception{mvc.perform(auth(put(path("/settings/notification"))).header("X-Correlation-ID","audit-correlation-46").contentType(MediaType.APPLICATION_JSON).content("{\"key\":\"digest\",\"value\":\"true\",\"valueType\":\"BOOLEAN\"}" )).andExpect(status().isOk());List<AuditLog> logs=auditLogs.findAllByCompanyIdOrderByCreatedAtDesc(owner.companyId(),org.springframework.data.domain.PageRequest.of(0,10));assertTrue(logs.stream().anyMatch(x->"audit-correlation-46".equals(x.getCorrelationId())));}

 private String path(String suffix){return "/api/companies/"+owner.companyId()+suffix;}private MockHttpServletRequestBuilder auth(MockHttpServletRequestBuilder b){return b.header("Authorization","Bearer "+owner.token());}
 private String rule(String name,String type,String schedule,String channel,Map<String,Object> params)throws Exception{return json.writeValueAsString(Map.of("name",name,"ruleType",type,"scheduleType",schedule,"notificationChannel",channel,"parameters",params,"active",true));}
 private UUID id(MvcResult r)throws Exception{return UUID.fromString(node(r).get("id").asText());}private JsonNode node(MvcResult r)throws Exception{return json.readTree(r.getResponse().getContentAsString());}
 private Workspace workspace(String prefix)throws Exception{String email=prefix+"-"+UUID.randomUUID()+"@abhay.test";MvcResult signup=mvc.perform(post("/api/auth/signup").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("name","Enterprise Owner","email",email,"password","StrongPass123!")))).andExpect(status().isCreated()).andReturn();String token=node(signup).get("accessToken").asText();MvcResult company=mvc.perform(post("/api/companies").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("legalName",prefix+" Company","tradeName",prefix+" Company","stateCode","27","industry","Services","financialYearStart","2026-04-01","financialYearEnd","2027-03-31")))).andExpect(status().isCreated()).andReturn();return new Workspace(token,UUID.fromString(node(company).get("id").asText()));}
 private String addViewer()throws Exception{String email="viewer-"+UUID.randomUUID()+"@abhay.test";MvcResult signup=mvc.perform(post("/api/auth/signup").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("name","Read Only","email",email,"password","StrongPass123!")))).andExpect(status().isCreated()).andReturn();mvc.perform(auth(post(path("/members"))).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("email",email,"role","VIEWER")))).andExpect(status().isCreated());return node(signup).get("accessToken").asText();}
 private record Workspace(String token,UUID companyId){}
}
